GET http://192.168.56.10:81

###
POST http://192.168.56.10:81 HTTP/1.1
content-type: application/json

{
 "_id": 9,
 "accountID": 12,
 "username": "billybob",
 "title_id": 8,
 "user_action": "pause",
 "date_and_time": "2022-02-01T08:00:00Z",
 "poi": "00:00:14",
 "toi": "Spacebar Pressed"
}
GET http://192.168.56.158:81

###
POST http://192.168.56.158:81 HTTP/1.1
content-type: application/json

{
 "_id": 8,
 "username": "lindaben",
 "title_id": 8,
 "user_action": "pause",
 "date_and_time": "07/03/2022 11:26AM",
 "point_of_interaction": "pause",
 "type_of_interaction": "keyboard"
}